# Generated by Django 5.2 on 2025-04-10 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyauthorization',
            name='password_hash',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='employeeauthorization',
            name='password',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='userauthorization',
            name='password',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
