# Generated by Django 5.2 on 2025-04-10 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_companyauthorization_password_hash_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyauthorization',
            old_name='password_hash',
            new_name='password',
        ),
    ]
