# Generated by Django 5.1.3 on 2024-12-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'application',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255, unique=True)),
                ('manager_surname', models.CharField(max_length=255)),
                ('manager_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('website', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyAuthorization',
            fields=[
                ('company_authorization_id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'db_table': 'company_authorization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyEmployee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=255)),
                ('employee_surname', models.CharField(max_length=255)),
                ('is_approved', models.IntegerField()),
            ],
            options={
                'db_table': 'company_employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyReview',
            fields=[
                ('company_review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.CharField(max_length=1)),
                ('message', models.CharField(blank=True, max_length=2000, null=True)),
                ('submitted_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'company_review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DisabilityDescription',
            fields=[
                ('disability_description_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('disability_certificate', models.TextField()),
            ],
            options={
                'db_table': 'disability_description',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DisabilityGroup',
            fields=[
                ('disability_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('disability_type', models.CharField(max_length=9)),
            ],
            options={
                'db_table': 'disability_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('education_id', models.AutoField(primary_key=True, serialize=False)),
                ('institution_name', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('field_of_study', models.CharField(max_length=255)),
                ('start_day', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'education',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeAuthorization',
            fields=[
                ('employee_authorization_id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'db_table': 'employee_authorization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeRequests',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('requested_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'employee_requests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobExperience',
            fields=[
                ('job_experience_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(max_length=2500)),
            ],
            options={
                'db_table': 'job_experience',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('resume_id', models.AutoField(primary_key=True, serialize=False)),
                ('pdf_file', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'resume',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('user_surname', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=7)),
                ('birthday_date', models.DateField()),
                ('phone_number', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserAuthorization',
            fields=[
                ('user_authorization_id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'db_table': 'user_authorization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('vacancy_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=5000)),
                ('requirements', models.CharField(max_length=1000)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job_type', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'vacancy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VacancyReview',
            fields=[
                ('vacancy_review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.CharField(max_length=1)),
                ('message', models.CharField(blank=True, max_length=2000, null=True)),
                ('submitted_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'vacancy_review',
                'managed': False,
            },
        ),
    ]
